/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 12+, use `process.report.getReport()` to detect musl
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'darwin':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'scanner.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./scanner.darwin-x64.node')
          } else {
            nativeBinding = require('@openobscure/scanner-napi-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'scanner.darwin-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./scanner.darwin-arm64.node')
          } else {
            nativeBinding = require('@openobscure/scanner-napi-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(join(__dirname, 'scanner.linux-x64-musl.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./scanner.linux-x64-musl.node')
            } else {
              nativeBinding = require('@openobscure/scanner-napi-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(join(__dirname, 'scanner.linux-x64-gnu.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./scanner.linux-x64-gnu.node')
            } else {
              nativeBinding = require('@openobscure/scanner-napi-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(join(__dirname, 'scanner.linux-arm64-musl.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./scanner.linux-arm64-musl.node')
            } else {
              nativeBinding = require('@openobscure/scanner-napi-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(join(__dirname, 'scanner.linux-arm64-gnu.node'))
          try {
            if (localFileExisted) {
              nativeBinding = require('./scanner.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('@openobscure/scanner-napi-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  // Fallback: try loading scanner.node directly (local dev build)
  try {
    nativeBinding = require('./scanner.node')
  } catch (e) {
    if (loadError) {
      throw loadError
    }
    throw e
  }
}

const { OpenObscureScanner } = nativeBinding

module.exports.OpenObscureScanner = OpenObscureScanner
