/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** A single PII match returned by `scanText()`. */
export interface ScanMatch {
  /** Byte offset start in the input string. */
  start: number
  /** Byte offset end in the input string. */
  end: number
  /** PII type identifier (e.g. "ssn", "email", "person", "location"). */
  piiType: string
  /** Detection confidence (0.0–1.0). Regex/keyword = 1.0, NER = model score. */
  confidence: number
  /** The raw matched text. */
  rawValue: string
}
/** Result of a `scanText()` call. */
export interface ScanResult {
  /** All PII matches found. */
  matches: Array<ScanMatch>
  /** Total scan time in microseconds. */
  timingUs: number
}
/** A single persuasion phrase match. */
export interface PersuasionMatchJs {
  category: string
  start: number
  end: number
  phrase: string
}
/** Result of a persuasion scan. */
export interface PersuasionScanResultJs {
  matches: Array<PersuasionMatchJs>
  timingUs: number
}
/**
 * Scan text for persuasion/manipulation phrases using the Rust dictionary.
 *
 * Returns all matches with category, offsets, and timing.
 * This is the R1 dictionary layer only (no R2 model inference).
 */
export declare function scanPersuasion(text: string): PersuasionScanResultJs
/**
 * Native PII scanner wrapping the Rust HybridScanner.
 *
 * Supports two modes:
 * - **Regex + keywords** (no model dir): detects 9 structured PII types
 * - **Full NER** (with model dir): adds person, location, organization,
 *   health, child detection (14 total types)
 */
export declare class OpenObscureScanner {
  /**
   * Create a new scanner.
   *
   * @param nerModelDir - Optional path to NER model directory containing
   *   `model_int8.onnx`, `vocab.txt`, and `label_map.json`. If omitted or
   *   models not found, falls back to regex + keywords only.
   */
  constructor(nerModelDir?: string | undefined | null)
  /**
   * Scan text for PII and return all matches with timing.
   *
   * @param text - The text to scan for PII.
   * @returns ScanResult with matches and timing.
   */
  scanText(text: string): ScanResult
  /** Check whether the NER model is loaded. */
  hasNer(): boolean
}
