// OpenObscureInterceptor.kt — OkHttp interceptor for Android (outbound-only)
// Sanitizes user messages in outbound chat requests. Response handling
// (restore + cognitive firewall) happens in ChatService after stream completes.
//
// Auto-generated requests (title generation, suggestion generation) are detected
// by model="auto" or stream=false with msg_count=1. These use isolated mappings
// so their disposable tokens don't pollute the conversation's mapping pool.
//
// Multimodal messages (OpenAI vision format): text parts are sanitized via NER,
// image parts (base64 or URL) are sanitized through the NSFW/face/OCR pipeline.

package your.app.package

import android.util.Base64
import android.util.Log
import kotlinx.serialization.json.*
import okhttp3.Interceptor
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import okhttp3.Response
import okio.Buffer
import uniffi.openobscure_core.*

class OpenObscureInterceptor : Interceptor {
    companion object {
        private const val TAG = "OO-Interceptor"
        // Separate client for fetching external image URLs — no interceptors to avoid recursion
        private val imageClient = OkHttpClient.Builder()
            .connectTimeout(10, java.util.concurrent.TimeUnit.SECONDS)
            .readTimeout(30, java.util.concurrent.TimeUnit.SECONDS)
            .build()
    }

    override fun intercept(chain: Interceptor.Chain): Response {
        val request = chain.request()

        val body = request.body ?: return chain.proceed(request)
        val contentType = body.contentType()
        if (contentType?.subtype != "json") return chain.proceed(request)

        val buffer = Buffer()
        body.writeTo(buffer)
        val bodyStr = buffer.readUtf8()

        val root = try {
            Json.parseToJsonElement(bodyStr).jsonObject
        } catch (_: Exception) {
            return chain.proceed(request)
        }

        val model = root["model"]?.jsonPrimitive?.contentOrNull ?: "unknown"
        val stream = root["stream"]?.jsonPrimitive?.booleanOrNull ?: false
        val msgCount = root["messages"]?.jsonArray?.size ?: 0

        // Auto-generated requests: title gen and suggestion gen use model="auto",
        // stream=false, and msg_count=1. These get isolated (disposable) mappings.
        val isAutoGenerated = model == "auto" || (!stream && msgCount == 1)

        val sanitizedBody = try {
            sanitizeRequestJson(root, isAutoGenerated)
        } catch (e: Exception) {
            // Fail-open: if sanitization crashes, forward original request
            Log.e(TAG, "[ERROR] sanitizeRequestJson failed: ${e.message}", e)
            bodyStr
        }

        val newRequest = request.newBuilder()
            .method(request.method, sanitizedBody.toRequestBody(contentType))
            .build()

        val response = chain.proceed(newRequest)

        // Log error responses for auto-generated requests to diagnose title gen failures
        if (isAutoGenerated && !response.isSuccessful) {
            val respBody = response.peekBody(2048)
            Log.e(TAG, "[AUTO-ERROR] HTTP ${response.code} for model=$model, url=${request.url}")
            Log.e(TAG, "[AUTO-ERROR] response: ${respBody.string().take(500)}")
        }

        return response
    }

    private fun sanitizeRequestJson(root: JsonObject, isAutoGenerated: Boolean): String {
        val mutableRoot = root.toMutableMap()
        val messages = root["messages"]?.jsonArray ?: return root.toString()
        val mgr = OpenObscureManager

        // Build ChatMessageFfi list for batch sanitization.
        // Multimodal messages are processed separately — text parts sanitized,
        // image parts run through the NSFW/face/OCR pipeline.
        val ffiMessages = mutableListOf<ChatMessageFfi>()
        val multimodalIndices = mutableSetOf<Int>()

        messages.forEachIndexed { idx, msg ->
            val obj = msg.jsonObject
            val role = obj["role"]?.jsonPrimitive?.contentOrNull ?: "user"
            val contentElement = obj["content"]

            val content: String
            if (contentElement == null) {
                multimodalIndices.add(idx)
                content = ""
            } else if (contentElement is JsonArray) {
                // Multimodal — will be sanitized part-by-part below
                multimodalIndices.add(idx)
                content = ""
            } else {
                content = try {
                    contentElement.jsonPrimitive.contentOrNull ?: ""
                } catch (_: Exception) {
                    multimodalIndices.add(idx)
                    ""
                }
            }
            ffiMessages.add(ChatMessageFfi(role = role, content = content))
        }

        // Auto-generated requests use isolated mappings — PII is still sanitized
        // but tokens are disposable and not merged into the conversation pool.
        val result = if (isAutoGenerated) {
            mgr.sanitizeMessagesIsolated(ffiMessages)
        } else {
            mgr.sanitizeMessages(ffiMessages)
        }

        // Rebuild JSON messages
        val sanitizedMessages = messages.mapIndexed { idx, msg ->
            if (idx in multimodalIndices) {
                // Multimodal message — sanitize each part individually
                sanitizeMultimodalMessage(msg.jsonObject, mgr, isAutoGenerated)
            } else {
                val sanitizedContent = result.messages[idx].content
                val obj = msg.jsonObject
                JsonObject(obj.toMutableMap().apply {
                    put("content", JsonPrimitive(sanitizedContent))
                })
            }
        }
        mutableRoot["messages"] = JsonArray(sanitizedMessages)
        return JsonObject(mutableRoot).toString()
    }

    /**
     * Sanitize a multimodal message (OpenAI vision format).
     * Text parts: run through PII scanner.
     * Image parts (base64 or URL): run through NSFW/face/OCR pipeline.
     *
     * Edge cases:
     * - External URL fetch failure: fail-open, pass original URL through
     * - Image sanitize failure: fail-open, pass original image bytes through
     * - Non-image parts (audio, etc.): pass through unchanged
     * - Empty text parts: pass through unchanged
     */
    private fun sanitizeMultimodalMessage(
        msgObj: JsonObject,
        mgr: OpenObscureManager,
        isAutoGenerated: Boolean
    ): JsonObject {
        val contentArray = msgObj["content"]?.jsonArray ?: return msgObj
        val role = msgObj["role"]?.jsonPrimitive?.contentOrNull ?: "user"

        val sanitizedParts = contentArray.map { part ->
            val partObj = part.jsonObject
            val type = partObj["type"]?.jsonPrimitive?.contentOrNull

            when (type) {
                "text" -> {
                    // Sanitize text content through PII scanner
                    val text = partObj["text"]?.jsonPrimitive?.contentOrNull ?: ""
                    if (text.isEmpty()) {
                        part
                    } else {
                        val sanitized = if (isAutoGenerated) {
                            sanitizeText(mgr.handle, text).sanitizedText
                        } else {
                            mgr.sanitize(text).sanitizedText
                        }
                        JsonObject(partObj.toMutableMap().apply {
                            put("text", JsonPrimitive(sanitized))
                        })
                    }
                }

                "image_url" -> {
                    // Sanitize image through NSFW/face/OCR pipeline
                    val imageUrlObj = partObj["image_url"]?.jsonObject
                    val url = imageUrlObj?.get("url")?.jsonPrimitive?.contentOrNull ?: ""

                    val sanitizedUrl = sanitizeImageUrl(url, mgr)
                    if (sanitizedUrl != null) {
                        JsonObject(partObj.toMutableMap().apply {
                            put("image_url", JsonObject(imageUrlObj!!.toMutableMap().apply {
                                put("url", JsonPrimitive(sanitizedUrl))
                            }))
                        })
                    } else {
                        part // fail-open: couldn't process, pass original
                    }
                }

                else -> part // unknown part type — pass through
            }
        }

        return JsonObject(msgObj.toMutableMap().apply {
            put("content", JsonArray(sanitizedParts))
        })
    }

    /**
     * Sanitize an image URL — handles both base64 data URIs and external URLs.
     * Returns sanitized base64 data URI, or null if processing failed (caller passes original).
     */
    private fun sanitizeImageUrl(url: String, mgr: OpenObscureManager): String? {
        val imageBytes: ByteArray

        if (url.startsWith("data:image/")) {
            // Inline base64: data:image/jpeg;base64,/9j/4AAQ...
            val commaIdx = url.indexOf(',')
            if (commaIdx < 0) return null

            val base64Data = url.substring(commaIdx + 1)
            imageBytes = try {
                Base64.decode(base64Data, Base64.DEFAULT)
            } catch (e: Exception) {
                Log.d(TAG, "[IMAGE] base64 decode failed: ${e.message}")
                return null
            }
            Log.d(TAG, "[IMAGE] inline base64: ${imageBytes.size} bytes")
        } else if (url.startsWith("http://") || url.startsWith("https://")) {
            // External URL — fetch image bytes then sanitize
            Log.d(TAG, "[IMAGE] fetching external URL: ${url.take(80)}...")
            imageBytes = try {
                val req = Request.Builder().url(url).build()
                val resp = imageClient.newCall(req).execute()
                if (!resp.isSuccessful) {
                    Log.d(TAG, "[IMAGE] fetch failed: HTTP ${resp.code}")
                    return null
                }
                resp.body?.bytes() ?: return null
            } catch (e: Exception) {
                Log.d(TAG, "[IMAGE] fetch failed: ${e.message}")
                return null
            }
            Log.d(TAG, "[IMAGE] fetched: ${imageBytes.size} bytes")
        } else {
            // Unknown URL scheme — pass through
            return null
        }

        // Run through NSFW/face/OCR pipeline
        val sanitized = mgr.sanitizeImage(imageBytes)

        // Re-encode as base64 data URI (always JPEG — Rust pipeline outputs JPEG)
        val sanitizedBase64 = Base64.encodeToString(sanitized, Base64.NO_WRAP)
        return "data:image/jpeg;base64,$sanitizedBase64"
    }
}
